// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/example/accordion.vue')['default']
    Aircraft: typeof import('./components/example/aircraft.vue')['default']
    Button: typeof import('./components/example/button.vue')['default']
    Click: typeof import('./components/example/click.vue')['default']
    CollapseTransition: typeof import('./components/CollapseTransition.vue')['default']
    Demo: typeof import('./components/example/demo.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FrostedGlass: typeof import('./components/example/frosted-glass.vue')['default']
    GradientBackground: typeof import('./components/example/gradient-background.vue')['default']
    GradientBorder: typeof import('./components/example/gradient-border.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./components/example/shape.vue')['default']
    SourceCode: typeof import('./components/SourceCode.vue')['default']
    Srcoll: typeof import('./components/example/srcoll.vue')['default']
    Tabs: typeof import('./components/example/tabs.vue')['default']
    TagSurround: typeof import('./components/example/tag-surround.vue')['default']
    Text: typeof import('./components/example/text.vue')['default']
    TextOverflow: typeof import('./components/example/text-overflow.vue')['default']
    Typewriter: typeof import('./components/example/typewriter.vue')['default']
  }
}
