// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollapseTransition: typeof import('./components/collapse-transition/index.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Demo: typeof import('./components/example/demo.vue')['default']
    Example: typeof import('./components/Example.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./components/example/shape.vue')['default']
    SourceCode: typeof import('./components/SourceCode/index.vue')['default']
  }
}
