// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CloseHandler: typeof import('./components/CloseHandler.vue')['default']
    CollapseTransition: typeof import('./components/CollapseTransition.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HiddenSourceSvg: typeof import('./components/Svg/HiddenSourceSvg.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showcase: typeof import('./components/Showcase.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SourceCode: typeof import('./components/SourceCode.vue')['default']
  }
}
